# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'


flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Imitate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'YTKNetwork'
  
    # Pods for Imitate
  install_all_flutter_pods(flutter_application_path)

  target 'ImitateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImitateUITests' do
    # Pods for testing
  end

end
